image: maven:3.3.9

pipelines:
  branches:
    experimental:
      - step:
          caches:
            - maven
          script: # Modify the commands below to build your repository.
            - mvn -B verify # -B batch mode makes Maven less verbose
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -B verify